version: '3'

services:

  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/slick-portfolio-svelte/src
    ports:
      - "3100:3100"
    command: ["npm", "run", "dev"]
    environment:
      - VITE_ENV=development
    networks:
      - main

  static-app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3200:80"
    environment:
      - VITE_ENV=production
    networks:
      - main

networks:
  main:
    driver: bridge